---
title: "Design of yasss"
author: "Phillip Labuschagne"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overall Design

yasss is designed to simulate genealogies which are stored in data.frames. A
high level summary of the core simulation functions are provided below:

sim_pop
- loop over number of generations
  - sim_next_gen
    - loop over all parents
      - mutator: mutate parent seq into offspring seq
  - fitness_evaluator

It quickly became clear that most simulations will involve many datasets
generated with distinct sets of arguments. Functionality to track this extra
structure was added to yasss.

## Managing multiple simulations

The genealogy data.frames rapidly become too large to store in memory. Thus
there are two different approaches to managing the data from multiple
simulations. The first is to store the full genealogies, which is useful for
smaller simulations and for troubleshooting. The second approach reduces memory
consumption by summarizing each genealogy as it is simulated and only saving the
summary metrics. The summary metrics include:
- the percentiles of the distribution,
- the average of all the pairwise distances,
- and, an estimate of the distribution as produced by density()

Another structure that exists in the data is a pair (or set) generated by
applying different fitness cutoffs to a genealogy. Now in theory both the
cutoff and the method in which the fitness is computed can be varied for the
same genealogy, but that is not currently supported. The computation of the
fitness is part of the simulation of the genealogy and modifying this
behaviour is not currently planned, but multiple fitness thresholds can be
considered, resulting in a set instead of a pair.

This complexity is tracked in the following data structures:
- arg_list: A list that contains the arguments for sim_pop *AND* a required
  fitness *AND* a label. Thus an arg_list contains enough information to produce a fit/unfit
  pair. The label will be used later to associate the simulated data with the
  arg_list that was used to produce it.
- dsum: Summary of the distance matrix (percentiles, avg, density). This is a
  list with an element for each distance matrix that was produced.
- gcol: A collection of genealogies. This is the main memory consuming
  culprit. It is just a string of genealogy data.frames rbinded together with
  extra columns added that tracks the genealogy_id, the argument_list that was
  used to produce it and the fitness requirement that had to be satisfied.














