# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_fibo <- function(s1, s2, n) {
    .Call('_yasss_cpp_fibo', PACKAGE = 'yasss', s1, s2, n)
}

cpp_fibo_df <- function(n, n_columns) {
    .Call('_yasss_cpp_fibo_df', PACKAGE = 'yasss', n, n_columns)
}

cpp_fibo_df_pass <- function(n, n_columns, foo) {
    .Call('_yasss_cpp_fibo_df_pass', PACKAGE = 'yasss', n, n_columns, foo)
}

cpp_mutator_uniform_fun <- function(parent, mu) {
    .Call('_yasss_cpp_mutator_uniform_fun', PACKAGE = 'yasss', parent, mu)
}

